// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChooseOption = { id: bigint, name: string, };

export type ExtendedChooseOption = { id: bigint, name: string, fields: { [key in string]?: string }, };
