// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoggedSessionDto = { username: string, email: string, role: string, tenant: string, };

export type LoginRequestDto = { email: string, password: string, };

export type RegisterNewTenantDto = { username: string, firstname: string, lastname: string, email: string, password: string, tenant: string, };
