// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChooseOption } from "../common/ChooseOption";
import type { DataTableRequestDto } from "../common/DataTable";
import type { ExtendedChooseOption } from "../common/ChooseOption";

export type TicketDto = { id: bigint, title: string, description: string, created_by: ChooseOption, assigned_to: ChooseOption, status: ExtendedChooseOption, };

export type TicketTableRequest = { dt_request: DataTableRequestDto, title: string | null, description: string | null, created_by: string | null, assigned_to: string | null, status: string | null, };
